# Generated by Django 5.1.7 on 2025-03-19 01:40

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('flavor_text', models.CharField(blank=True, max_length=200)),
                ('img_url', models.CharField(blank=True, max_length=100)),
                ('rarity', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=1)),
                ('rarity_display', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.Value('('), django.db.models.functions.text.Chr('rarity'), models.Value('★)')), output_field=models.CharField(max_length=30))),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacha.account')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacha.item')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='items',
            field=models.ManyToManyField(through='gacha.AccountItem', to='gacha.item'),
        ),
    ]
