# Generated by Django 5.1.5 on 2025-01-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
