# Generated by Django 5.1.7 on 2025-03-19 01:45

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rarity_display',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.Value('('), django.db.models.functions.comparison.Cast('rarity', models.CharField()), models.Value('★)')), output_field=models.CharField(max_length=30)),
        ),
        migrations.AddField(
            model_name='item',
            name='rarity_display',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.Value('('), django.db.models.functions.comparison.Cast('rarity', models.CharField()), models.Value('★)')), output_field=models.CharField(max_length=30)),
        ),
    ]
