# Generated by Django 5.1.5 on 2025-03-08 04:52

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0002_remove_account_username_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rarity_display',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.functions.text.Concat(models.Value('('), 'rarity', models.Value('★)')), output_field=models.CharField(max_length=30)),
        ),
    ]
