# Generated by Django 5.1.5 on 2025-03-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0003_item_rarity_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flavor_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='img_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
